import type { Company } from "./companies.types";

// 강남 지역 IT 대기업
const gangnamCompanies: Company[] = [
  {
    id: "c1",
    name: "네이버",
    industry: "검색/플랫폼",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/22/Naver_Logotype.svg",
    address: "서울특별시 강남구 테헤란로 152",
    latitude: 37.3595704,
    longitude: 127.105399,
    area: "강남",
    description: "검색과 클라우드를 중심으로 다양한 서비스를 운영하는 테크 기업",
    siteUrl: "https://recruit.navercorp.com/",
    isFavorite: false,
  },
  {
    id: "c2",
    name: "카카오",
    industry: "플랫폼/메신저",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Kakao_logo.svg",
    address: "서울특별시 강남구 테헤란로 152",
    latitude: 37.3616,
    longitude: 127.1054,
    area: "강남",
    description: "메신저를 기반으로 생활 전반의 서비스를 확장하고 있는 플랫폼 기업",
    siteUrl: "https://careers.kakao.com/jobs",
    isFavorite: false,
  },
  {
    id: "c3",
    name: "토스",
    industry: "금융",
    logoUrl: "https://static.toss.im/logos/png/4x/toss-icon.png",
    address: "서울특별시 강남구 테헤란로 142",
    latitude: 37.3575,
    longitude: 127.1053,
    area: "강남",
    description: "금융 서비스를 혁신하는 핀테크 기업",
    siteUrl: "https://toss.im/career",
    isFavorite: false,
  },
  {
    id: "c4",
    name: "라인",
    industry: "메신저/커뮤니케이션",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/41/LINE_logo.svg",
    address: "서울특별시 강남구 테헤란로 231",
    latitude: 37.3635,
    longitude: 127.1055,
    area: "강남",
    description: "전 세계 2억 명 이상의 유저가 사용하는 글로벌 메신저",
    siteUrl: "https://careers.linecorp.com/",
    isFavorite: false,
  },
  {
    id: "c5",
    name: "당근마켓",
    industry: "커머스/중고거래",
    logoUrl: "https://www.daangn.com/favicon.ico",
    address: "서울특별시 강남구 테헤란로 427",
    latitude: 37.3655,
    longitude: 127.1056,
    area: "강남",
    description: "동네 기반 중고거래와 생활 서비스를 제공하는 플랫폼",
    siteUrl: "https://about.daangn.com/jobs/",
    isFavorite: false,
  },
  {
    id: "c6",
    name: "우아한형제들",
    industry: "배달/커머스",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Woowa_Brothers_logo.svg",
    address: "서울특별시 강남구 테헤란로 133",
    latitude: 37.3555,
    longitude: 127.1052,
    area: "강남",
    description: "배달의민족을 운영하는 배달 플랫폼 기업",
    siteUrl: "https://career.woowahan.com/",
    isFavorite: false,
  },
];

// 판교 지역 IT 대기업
const pangyoCompanies: Company[] = [
  {
    id: "c7",
    name: "쿠팡",
    industry: "커머스/물류",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Coupang_logo.svg",
    address: "경기도 성남시 분당구 정자일로 95",
    latitude: 37.3947,
    longitude: 127.1112,
    area: "판교",
    description: "로켓배송을 중심으로 대규모 물류·데이터 시스템을 운영하는 커머스 기업",
    siteUrl: "https://rocketyourcareer.coupang.com/",
    isFavorite: false,
  },
  {
    id: "c8",
    name: "넥슨",
    industry: "게임",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Nexon_logo.svg",
    address: "경기도 성남시 분당구 판교로 256",
    latitude: 37.3967,
    longitude: 127.1114,
    area: "판교",
    description: "온라인 게임 개발 및 서비스를 제공하는 글로벌 게임 기업",
    siteUrl: "https://career.nexon.com/",
    isFavorite: false,
  },
  {
    id: "c9",
    name: "NC소프트",
    industry: "게임",
    logoUrl: "https://www.ncsoft.com/favicon.ico",
    address: "경기도 성남시 분당구 판교로 256",
    latitude: 37.3927,
    longitude: 127.1110,
    area: "판교",
    description: "MMORPG 게임 개발 및 서비스를 제공하는 게임 기업",
    siteUrl: "https://career.ncsoft.com/",
    isFavorite: false,
  },
  {
    id: "c10",
    name: "야놀자",
    industry: "여행/숙박",
    logoUrl: "https://www.yanolja.com/favicon.ico",
    address: "경기도 성남시 분당구 판교로 256",
    latitude: 37.3987,
    longitude: 127.1116,
    area: "판교",
    description: "여행 및 숙박 예약 플랫폼을 운영하는 OTA 기업",
    siteUrl: "https://careers.yanolja.com/",
    isFavorite: false,
  },
  {
    id: "c11",
    name: "업스테이지",
    industry: "AI/데이터",
    logoUrl: "https://www.upstage.ai/favicon.ico",
    address: "경기도 성남시 분당구 판교로 256",
    latitude: 37.3907,
    longitude: 127.1108,
    area: "판교",
    description: "최신 LLM 기술을 활용한 AI 솔루션을 제공하는 기업",
    siteUrl: "https://www.upstage.ai/careers",
    isFavorite: false,
  },
  {
    id: "c12",
    name: "카카오뱅크",
    industry: "금융/핀테크",
    logoUrl: "https://www.kakaobank.com/favicon.ico",
    address: "경기도 성남시 분당구 판교로 256",
    latitude: 37.3967,
    longitude: 127.1110,
    area: "판교",
    description: "모바일 중심의 인터넷 은행 서비스를 제공하는 핀테크 기업",
    siteUrl: "https://careers.kakaobank.com/",
    isFavorite: false,
  },
];

export const mockCompanies: Company[] = [...gangnamCompanies, ...pangyoCompanies];

// 지역별 회사 목록
export const getCompaniesByArea = (area: "강남" | "판교"): Company[] => {
  return mockCompanies.filter((company) => company.area === area);
};
